name: bank

networks:
    dev:
        driver: bridge

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_NAME: 'postgres'
            POSTGRES_PASSWORD: 'SuperStrongPassword'
        ports:
            - "5433:5432"
        networks:
            - dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
    
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak
        ports:
            - "8010:8080"
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: superpassword123
        command:
             - start-dev
             - --import-realm
        networks:
            - dev
        volumes:
            - ./config:/opt/keycloak/data/import

    rabbitMq:
        container_name: rabbitMq
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - dev
        volumes:
            - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
            - ./config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
            - rabbitmq-data:/var/lib/rabbitmq

    account-service:
        image: ${DOCKER_REGISTRY-}account-service
        container_name: account-service 
        build: 
            context: .
            dockerfile: ./src/AccountService/Dockerfile
        networks:
            - dev
        ports:
            - "80:8080"
        depends_on:
        - keycloak

volumes:
    config:
    postgres-data:
    rabbitmq-data: